// <auto-generated />
using Generator.Server;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Generator.Services.Migrations.Generator
{
    [DbContext(typeof(GeneratorContext))]
    [Migration("20230406122209_TableFix1")]
    partial class TableFix1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Generator.Shared.Models.ComponentModels.COMPONENT_BASE", b =>
                {
                    b.Property<int>("CB_ROWID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CB_ROWID"), 1L, 1);

                    b.Property<string>("CB_CODE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CB_COMMAND_TYPE")
                        .HasColumnType("int");

                    b.Property<string>("CB_COMPONENT_TYPE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CB_DATABASE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CB_DESCRIPTION")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CB_SQL_COMMAND")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CB_TABLE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CB_TITLE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CB_ROWID");

                    b.ToTable("COMPONENT_BASE");
                });

            modelBuilder.Entity("Generator.Shared.Models.ComponentModels.DISPLAY_FIELDS", b =>
                {
                    b.Property<int>("DF_ROWID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DF_ROWID"), 1L, 1);

                    b.Property<int>("DF_COMPONENT_REFNO")
                        .HasColumnType("int");

                    b.Property<string>("DF_DATABASE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DF_FIELD_NAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DF_STORED_PROCEDURE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DF_TITLE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DF_ROWID");

                    b.HasIndex("DF_COMPONENT_REFNO");

                    b.ToTable("DISPLAY_FIELDS");
                });

            modelBuilder.Entity("Generator.Shared.Models.ComponentModels.PERMISSIONS", b =>
                {
                    b.Property<int>("PER_ROWID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PER_ROWID"), 1L, 1);

                    b.Property<string>("PER_AUTH_CODE")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("PER_COMPONENT_REFNO")
                        .HasColumnType("int");

                    b.Property<string>("PER_COMP_AUTH_CODE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PER_COMP_TYPE")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PER_DESCRIPTION")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PER_ROWID");

                    b.HasIndex("PER_COMPONENT_REFNO", "PER_AUTH_CODE")
                        .IsUnique()
                        .HasFilter("[PER_AUTH_CODE] IS NOT NULL");

                    b.ToTable("PERMISSIONS");
                });

            modelBuilder.Entity("Generator.Shared.Models.ComponentModels.BUTTONS_BASE", b =>
                {
                    b.HasBaseType("Generator.Shared.Models.ComponentModels.COMPONENT_BASE");

                    b.Property<int>("BB_PAGE_REFNO")
                        .HasColumnType("int");

                    b.HasIndex("BB_PAGE_REFNO");

                    b.ToTable("BUTTONS_BASE");
                });

            modelBuilder.Entity("Generator.Shared.Models.ComponentModels.PAGES_M", b =>
                {
                    b.HasBaseType("Generator.Shared.Models.ComponentModels.COMPONENT_BASE");

                    b.Property<bool>("PM_CREATE")
                        .HasColumnType("bit");

                    b.Property<bool>("PM_DELETE")
                        .HasColumnType("bit");

                    b.Property<bool>("PM_READ")
                        .HasColumnType("bit");

                    b.Property<bool>("PM_UPDATE")
                        .HasColumnType("bit");

                    b.ToTable("PAGES_M");
                });

            modelBuilder.Entity("Generator.Shared.Models.ComponentModels.GRID_BUTTONS", b =>
                {
                    b.HasBaseType("Generator.Shared.Models.ComponentModels.BUTTONS_BASE");

                    b.ToTable("GRID_BUTTONS");
                });

            modelBuilder.Entity("Generator.Shared.Models.ComponentModels.HEADER_BUTTONS", b =>
                {
                    b.HasBaseType("Generator.Shared.Models.ComponentModels.BUTTONS_BASE");

                    b.ToTable("HEADER_BUTTONS");
                });

            modelBuilder.Entity("Generator.Shared.Models.ComponentModels.PAGES_D", b =>
                {
                    b.HasBaseType("Generator.Shared.Models.ComponentModels.PAGES_M");

                    b.Property<int>("PD_M_REFNO")
                        .HasColumnType("int");

                    b.HasIndex("PD_M_REFNO")
                        .IsUnique()
                        .HasFilter("[PD_M_REFNO] IS NOT NULL");

                    b.ToTable("PAGES_D");
                });

            modelBuilder.Entity("Generator.Shared.Models.ComponentModels.DISPLAY_FIELDS", b =>
                {
                    b.HasOne("Generator.Shared.Models.ComponentModels.COMPONENT_BASE", null)
                        .WithMany("DISPLAY_FIELDS")
                        .HasForeignKey("DF_COMPONENT_REFNO")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Generator.Shared.Models.ComponentModels.PERMISSIONS", b =>
                {
                    b.HasOne("Generator.Shared.Models.ComponentModels.COMPONENT_BASE", null)
                        .WithMany("PERMISSIONS")
                        .HasForeignKey("PER_COMPONENT_REFNO")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Generator.Shared.Models.ComponentModels.BUTTONS_BASE", b =>
                {
                    b.HasOne("Generator.Shared.Models.ComponentModels.PAGES_M", null)
                        .WithMany("BUTTONS_BASE")
                        .HasForeignKey("BB_PAGE_REFNO")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Generator.Shared.Models.ComponentModels.COMPONENT_BASE", null)
                        .WithOne()
                        .HasForeignKey("Generator.Shared.Models.ComponentModels.BUTTONS_BASE", "CB_ROWID")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Generator.Shared.Models.ComponentModels.PAGES_M", b =>
                {
                    b.HasOne("Generator.Shared.Models.ComponentModels.COMPONENT_BASE", null)
                        .WithOne()
                        .HasForeignKey("Generator.Shared.Models.ComponentModels.PAGES_M", "CB_ROWID")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Generator.Shared.Models.ComponentModels.GRID_BUTTONS", b =>
                {
                    b.HasOne("Generator.Shared.Models.ComponentModels.BUTTONS_BASE", null)
                        .WithOne()
                        .HasForeignKey("Generator.Shared.Models.ComponentModels.GRID_BUTTONS", "CB_ROWID")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Generator.Shared.Models.ComponentModels.HEADER_BUTTONS", b =>
                {
                    b.HasOne("Generator.Shared.Models.ComponentModels.BUTTONS_BASE", null)
                        .WithOne()
                        .HasForeignKey("Generator.Shared.Models.ComponentModels.HEADER_BUTTONS", "CB_ROWID")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Generator.Shared.Models.ComponentModels.PAGES_D", b =>
                {
                    b.HasOne("Generator.Shared.Models.ComponentModels.PAGES_M", null)
                        .WithOne()
                        .HasForeignKey("Generator.Shared.Models.ComponentModels.PAGES_D", "CB_ROWID")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("Generator.Shared.Models.ComponentModels.PAGES_M", null)
                        .WithMany("PAGES_D")
                        .HasForeignKey("PD_M_REFNO")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Generator.Shared.Models.ComponentModels.COMPONENT_BASE", b =>
                {
                    b.Navigation("DISPLAY_FIELDS");

                    b.Navigation("PERMISSIONS");
                });

            modelBuilder.Entity("Generator.Shared.Models.ComponentModels.PAGES_M", b =>
                {
                    b.Navigation("BUTTONS_BASE");

                    b.Navigation("PAGES_D");
                });
#pragma warning restore 612, 618
        }
    }
}
