version: '3.4'

services:
  generator.service:
    image: ${DOCKER_REGISTRY-}generator
    build:
      context: .
      dockerfile: Generator.Service/Dockerfile

  generator.server:
    image: ${DOCKER_REGISTRY-}generator
    build:
      context: .
      dockerfile: Generator.Server/Dockerfile

